# .gitpod.yml
image: gitpod/workspace-python:latest

tasks:
  - name: Setup & Run Streamlit
    init: |
      pip install --upgrade pip
      pip install openai streamlit
    command: |
      streamlit run app.py \
        --server.port 8501 \
        --server.address 0.0.0.0

env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}

ports:
  - port: 8501
    onOpen: open-preview
    visibility: public
    protocol: http

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.vscode-streamlit