# .gitpod/automations.yaml
tasks:
  start-streamlit:
    name: Start Streamlit App
    command: |
      streamlit run app.py \
        --server.port 8501 \
        --server.address 0.0.0.0
    triggeredBy:
      - postDevcontainerStart
